// foreignStocks (isUSD: true)
export const foreignStocks = [
  {
    name: "BROADCOM INC",
    symbol: "AVGO",
    price: "202.13",
    logo: "https://s3-symbol-logo.tradingview.com/broadcom--big.svg",
    isUSD: true,
    about: `is an American designer, developer, manufacturer and global supplier of a wide range of semiconductor and infrastructure software products.`,
  },
  {
    name: "NVIDIA Corporation",
    symbol: "NVDA",
    price: "118.58",
    logo: "https://s3-symbol-logo.tradingview.com/nvidia--big.svg",
    isUSD: true,
    about: `is an American multinational technology company incorporated in Delaware and based in Santa Clara, California. It designs graphics processing units (GPUs) for the gaming and professional markets, as well as system on a chip units (SoCs) for the mobile computing and automotive market.`,
  },
  {
    name: "Apple Inc",
    symbol: "AAPL",
    price: "230.01",
    logo: "https://img.icons8.com/?size=100&id=30840&format=png",
    isUSD: true,
    about: `is an American multinational technology company that specializes in consumer electronics, computer software, and online services.`,
  },
  {
    name: "Microsoft",
    symbol: "MSFT",
    price: "434.56",
    logo: "https://img.icons8.com/?size=48&id=22989&format=png",
    isUSD: true,
    about: `is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.`,
  },
  {
    name: "Amazon.com Inc",
    symbol: "AMZN",
    price: "235.42",
    logo: "https://s3-symbol-logo.tradingview.com/amazon--big.svg",
    isUSD: true,
    about: `is an American multinational technology company which focuses on e-commerce, cloud computing, digital streaming, and artificial intelligence.`,
  },
  {
    name: "Tesla, Inc",
    symbol: "TSLA",
    price: "397.15",
    logo: "https://img.icons8.com/?size=48&id=34784&format=png",
    isUSD: true,
    about: `is an American electric vehicle and clean energy company based in Palo Alto, California. Tesla's current products include electric cars, battery energy storage from home to grid-scale, solar panels and solar roof tiles, as well as other related products and services.`,
  },
  {
    name: "META Platforms Inc",
    symbol: "META",
    price: "659.88",
    logo: "https://s3-symbol-logo.tradingview.com/meta-platforms--big.svg",
    isUSD: true,
    about: `is an American technology conglomerate. It was founded by Mark Zuckerberg, along with his fellow roommates and students at Harvard College, who were Eduardo Saverin, Andrew McCollum, Dustin Moskovitz, and Chris Hughes, originally as TheFacebook.com—today's Facebook, a popular global social networking service.`,
  },
  {
    name: "ALPHABET INC",
    symbol: "GOOGL",
    price: "193.77",
    logo: "https://s3-symbol-logo.tradingview.com/alphabet--big.svg",
    isUSD: true,
    about: `is an American multinational conglomerate that was created through a corporate restructuring of Google on October 2, 2015. The company is now the parent company of Google and several former Google subsidiaries.`,
  },
  {
    name: "NETFLIX INC",
    symbol: "NFLX",
    price: "971.89",
    logo: "https://s3-symbol-logo.tradingview.com/netflix--big.svg",
    isUSD: true,
    about: `is an American over-the-top content platform and production company headquartered in Los Gatos, California. Netflix was founded in 1997 by Reed Hastings and Marc Randolph in Scotts Valley, California.`,
  },
  {
    name: "BETTERSOURCE",
    symbol: "BET",
    price: "30.01",
    logo: "/BETTERSOURCE(FS).png",
    isUSD: true,
    about: `searches the market for deals on furniture that meets the needs of our customers. The main part of our business is bringing in liquidation items from offices that have either downsized or closed. Since we know we can’t fill all of our customers’ needs with used furniture, we have gone searching for the best deals on some new, quality items.`,
  },
  {
    name: "Engazaat",
    symbol: "ENG",
    price: "22.60",
    logo: "/Engazaat.png",
    isUSD: true,
    about: `Capitalizing on a family business legacy that goes back to more than 40 years, the Egyptian based venture Engazaat is co-founded by three brothers, and growing regionally as the first integrated independent power and water producer (IPWP), enabling communities with affordable tech-enabled solar energy, and water utility`,
  },
  // Add more foreign stocks if needed
];