// localStocks (isUSD: false)
export const localStocks = [
    {
      name: "AL-HABIB",
      symbol: "ALHA",
      price: "50.23",
      logo: "/AL-HABIB.png",
      isUSD: false,
      about: `We established Alhabib with one focus: to build a company that can compete with large construction firms while operating with the flexibility and customer-focus of a small, family-run business. We call it personal business values with a big business approach. Today, most of our business comes from a core group of legacy clients: a testament to our commitment to building strong, long-term working relationships.`,
    },
    {
      name: "ANASSET",
      symbol: "ANAS",
      price: "10.22",
      logo: "/ANASSET.png",
      isUSD: false,
      about: `Company Limited is a pioneer of LPG marketing and distribution in Ghana, boasting a legacy of leadership since our establishment in 1994. Originating from a modest household garage, we evolved from a retailer of pre-filled LPG cylinders to a dynamic force in the industry. Our swift expansion led to official recognition as a licensed LPG marketing company.`,
    },
    {
      name: "ARANDAA",
      symbol: "ARAN",
      price: "20.33",
      logo: "/ARANDA.png",
      isUSD: false,
      about: `is one of the leading blanket suppliers in the country. We have a large collection of quality blankets and throws which includes stylish and classic designs. Our designs combined with the commitment to on-going product development, has enabled us to secure our place in the competitive global market. All our blankets are produced using the highest quality standards, which is why Aranda is the producer of some of the finest fur-pile products in the world.`,
    },
    {
      name: "DANSOAA",
      symbol: "DANS",
      price: "16.52",
      logo: "/DANSOAA.png",
      isUSD: false,
      about: `is a leading manufacturer of quality blankets and throws. We have a large collection of quality blankets and throws which includes stylish and classic designs.`,
    },
    {
      name: "eva-well-cables",
      symbol: "EVA",
      price: "9.08",
      logo: "/eva-well-cables.jpg",
      isUSD: false,
      about: `is a leading manufacturer of quality cables. We have a large collection of quality cables which includes stylish and classic designs.`,
    },
    {
      name: "OLAM AGRI",
      symbol: "OLAM",
      price: "5.38",
      logo: "/OLAM AGRI.png",
      isUSD: false,
      about: `Whether it's working with rice farmers in Asia, sourcing cotton in Australia, or producing value-added products in Africa, we help our customers around the world meet the increasing demand for food, feed and fibre.`,
    },
    {
      name: "PEA.FM",
      symbol: "PEA",
      price: "2.01",
      logo: "/OPEA.FM.png",
      isUSD: false,
      about: `Radio stations streaming live on the internet. Over 25,000 stations worldwide. Listen live world best online free radio station. Listen to music from thousands of internet radio stations streaming live right now. Search or browse all your favourite music genres. The most popular FM stations and the internet radio stations of different genres are collected in the online directory of the radio stations.`,
    },
    {
      name: "ROHA PACK",
      symbol: "ROHA",
      price: "8.22",
      logo: "/ROHA-PACK .png",
      isUSD: false,
      about: `Established in 2003, Roha Pack PLC is one of the leading PET preforms in Ethiopia. Roha Pack supplies preforms to customers in various forms, such as bottled water, ready-to-drink beverages, carbonated drinks, detergents, edible oil, confectionery, and pharmaceutical segments. We have cutting-edge technology, hands-on skill, and a high-tech laboratory. We at Roha Pack PLC ensure our customers that all our products meet international standards.`,
    },
    {
      name: "SILKBLUME",
      symbol: "SILK",
      price: "5.23",
      logo: "/SILKBLUME.png",
      isUSD: false,
      about: `is a boutique silk flower sales or subscription business founded on the conviction that silk flowers are just as beautiful as their fresh flower counterparts but far more practical and eco-friendly.`,
    },
    {
      name: "manganese metal co",
      symbol: "MMC",
      price: "12.61",
      logo: "/MMC’s .png",
      isUSD: false,
      about: `refinery is situated in Mbombela (Nelspruit), South Africa. In operation since 1974, we are the world’s only non-China based producer of high grade electrolytic manganese metal (EMM) and the world’s largest refinery of 99.9% (selenium-free) EMM.`,
    },
  ];
  